#!/usr/bin/env node

/**
 * Ferrum C ABI TurboModule Bridge Generator
 *
 * This script runs as part of the podspec script_phase to generate
 * C ABI wrapper functions for all TurboModules after standard RN codegen.
 *
 * It reads JSON schemas produced by react-native-codegen and emits
 * C++ files that wrap each module method as a C ABI function.
 */

'use strict';

const fs = require('fs');
const path = require('path');

/**
 * Generator function conforming to RNCodegen's GenerateFunction signature.
 * Returns a Map<filename, content> of generated files.
 */
function generateFerrumABIBridges(
  libraryName,
  schema,
  packageName,
  assumeNonnull,
  headerPrefix,
  includeGetDebugPropsImplementation
) {
  const files = new Map();

  // Only process native modules
  if (!schema.modules) {
    return files;
  }

  const modules = schema.modules;
  let cppContent = generateCppBridges(libraryName, modules);
  let hContent = generateHeaderRegistry(libraryName, modules);

  files.set(`${libraryName}FerrumABIBridges.cpp`, cppContent);
  files.set(`${libraryName}FerrumABIRegistry.h`, hContent);

  return files;
}

/**
 * Generate C++ bridge functions for each module method.
 * Each function has the signature:
 *   static HermesABIValueOrError ferrum_ModuleName_methodName(...)
 */
function generateCppBridges(libraryName, modules) {
  let cpp = `// @generated by ferrum-codegen.js
#include <memory>
#include <string>
#include <cstring>
#include <unordered_map>
#include "hermes_abi.h"

// Forward declare the borrowed Hermes runtime wrapper (defined in FerrumRuntimeFactory)
extern "C" {
  const HermesABIValue* hermes_abi_getBool(const HermesABIValue* value);
  const HermesABIValue* hermes_abi_getNumber(const HermesABIValue* value);
  const HermesABIValue* hermes_abi_getString(const HermesABIValue* value, char* buffer, size_t size);
  const HermesABIValue* hermes_abi_createBool(int value);
  const HermesABIValue* hermes_abi_createNumber(double value);
  const HermesABIValue* hermes_abi_createString(const char* str);
  const HermesABIValue* hermes_abi_createUndefined();
}

namespace facebook::react::ferrum {

// Registry of all C ABI bridges: map<moduleName, map<methodName, function>>
using BridgeFunction = const HermesABIValue* (*)(
    void* moduleInstance,
    const HermesABIValue* args,
    size_t count
);

struct BridgeRegistry {
  std::string moduleName;
  std::unordered_map<std::string, BridgeFunction> methods;
};

static std::unordered_map<std::string, BridgeRegistry>& getBridgeRegistry() {
  static std::unordered_map<std::string, BridgeRegistry> registry;
  return registry;
}

// Macro to register a bridge function
#define FERRUM_REGISTER_ABI_BRIDGE(module_name, method_name, func) \\
  do { \\
    auto& registry = getBridgeRegistry(); \\
    if (registry.find(module_name) == registry.end()) { \\
      registry[module_name] = BridgeRegistry{module_name, {}}; \\
    } \\
    registry[module_name].methods[method_name] = func; \\
  } while (0)

// Helper: retrieve a bridge function by module and method name
inline const BridgeFunction* getBridge(const std::string& moduleName, const std::string& methodName) {
  auto& registry = getBridgeRegistry();
  auto it = registry.find(moduleName);
  if (it == registry.end()) return nullptr;

  auto methodIt = it->second.methods.find(methodName);
  if (methodIt == it->second.methods.end()) return nullptr;

  return &methodIt->second;
}

} // namespace facebook::react::ferrum

`;

  // Generate bridge functions for each module
  Object.keys(modules).forEach((moduleName) => {
    const moduleSpec = modules[moduleName];
    if (!moduleSpec.methods) return;

    Object.keys(moduleSpec.methods).forEach((methodName) => {
      const method = moduleSpec.methods[methodName];
      const returnType = method.returnType ? method.returnType.type : 'void';
      const params = method.params || [];

      cpp += generateBridgeFunction(moduleName, methodName, returnType, params);
    });
  });

  // Generate registration calls
  cpp += `

namespace facebook::react::ferrum {

// Initialize all bridge registrations
void initializeFerrumABIBridges() {
`;

  Object.keys(modules).forEach((moduleName) => {
    const moduleSpec = modules[moduleName];
    if (!moduleSpec.methods) return;

    Object.keys(moduleSpec.methods).forEach((methodName) => {
      cpp += `  FERRUM_REGISTER_ABI_BRIDGE("${moduleName}", "${methodName}", ferrum_${moduleName}_${methodName});\n`;
    });
  });

  cpp += `}

} // namespace facebook::react::ferrum
`;

  return cpp;
}

/**
 * Generate a single bridge function for a module method.
 * This is a stub implementation — the actual module instance lookup
 * and ObjC method invocation will be implemented in the runtime proxy.
 */
function generateBridgeFunction(moduleName, methodName, returnType, params) {
  const sanitizedMethod = methodName.charAt(0).toUpperCase() + methodName.slice(1);
  const funcName = `ferrum_${moduleName}_${sanitizedMethod}`;

  let params_str = params.map((p, i) => `bool arg${i}`).join(', ');
  if (params_str) params_str = ', ' + params_str;

  let cpp = `
// Bridge: ${moduleName}.${methodName}
// Returns: ${returnType}
static const HermesABIValue* ${funcName}(
    void* moduleInstance,
    const HermesABIValue* args,
    size_t count) {
  // Placeholder: Runtime proxy will:
  // 1. Look up ObjC module instance from moduleInstance
  // 2. Extract args from Hermes ABI values
  // 3. Call ObjC method via objc_msgSend
  // 4. Convert result back to Hermes ABI value

  if (count < ${params.length}) {
    return hermes_abi_createUndefined();
  }

  // TODO: Actual method invocation
  return hermes_abi_createUndefined();
}

`;

  return cpp;
}

/**
 * Generate header file with registry declaration.
 */
function generateHeaderRegistry(libraryName, modules) {
  let header = `// @generated by ferrum-codegen.js
#pragma once

#include <string>
#include <unordered_map>
#include "hermes_abi.h"

namespace facebook::react::ferrum {

using BridgeFunction = const HermesABIValue* (*)(
    void* moduleInstance,
    const HermesABIValue* args,
    size_t count
);

struct BridgeRegistry {
  std::string moduleName;
  std::unordered_map<std::string, BridgeFunction> methods;
};

std::unordered_map<std::string, BridgeRegistry>& getBridgeRegistry();
const BridgeFunction* getBridge(const std::string& moduleName, const std::string& methodName);
void initializeFerrumABIBridges();

} // namespace facebook::react::ferrum
`;

  return header;
}

module.exports = {
  generate: generateFerrumABIBridges,
};
