// FerrumCppRuntime.mm — C++ function registry + JSI bridge.
//
// 1. Bridge files call rna_register_sync/async at +load time.
// 2. When the JS runtime is ready, we install global.__rna with callSync/callAsync.
// 3. JS shims generated by the Metro transformer call global.__rna.callSync(...).

#import <Foundation/Foundation.h>
#include <jsi/jsi.h>
#if DEBUG
#include <dlfcn.h>  // Dev only — loadDylib uses dlopen for hot-reload
#endif
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <mutex>
#include <vector>

#import "FerrumCppRuntime.h"

using namespace facebook;

// ─── Registry ──────────────────────────────────────────────────────────

struct FnEntry {
  RNASyncFn syncFn = nullptr;
  RNAAsyncFn asyncFn = nullptr;
};

// key = "moduleId::fnName"
static std::unordered_map<std::string, FnEntry>& getRegistry() {
  static std::unordered_map<std::string, FnEntry> reg;
  return reg;
}

static std::string makeKey(const char* moduleId, const char* fnName) {
  return std::string(moduleId) + "::" + fnName;
}

extern "C" void rna_register_sync(const char* moduleId, const char* fnName, RNASyncFn fn) {
  getRegistry()[makeKey(moduleId, fnName)].syncFn = fn;
  NSLog(@"[FerrumCpp] registered sync: %s::%s", moduleId, fnName);
}

extern "C" void rna_register_async(const char* moduleId, const char* fnName, RNAAsyncFn fn) {
  getRegistry()[makeKey(moduleId, fnName)].asyncFn = fn;
  NSLog(@"[FerrumCpp] registered async: %s::%s", moduleId, fnName);
}

// ─── Component render registry ────────────────────────────────────────

static std::unordered_map<std::string, FerrumRenderFn>& getRenderRegistry() {
  static std::unordered_map<std::string, FerrumRenderFn> reg;
  return reg;
}

extern "C" void ferrum_register_render(const char* componentId, FerrumRenderFn fn) {
  getRenderRegistry()[std::string(componentId)] = fn;
  NSLog(@"[FerrumCpp] registered render: %s", componentId);
}

// ─── Props storage ─────────────────────────────────────────────────────
// Props are snapshotted from JSI immediately in setComponentProps into a
// plain jsi::Object that persists. A jsi::Runtime* is stored for access.
// The snapshot is a DEEP COPY as a new JS object to avoid GC issues.

static jsi::Runtime* g_runtime = nullptr;

// Store the STRINGIFIED props as a plain C++ string map.
// This avoids ALL JSI lifetime issues — no stored jsi::Object references.
struct PropsSnapshot {
  std::unordered_map<std::string, std::string> strings;
  std::unordered_map<std::string, double> numbers;
  std::unordered_map<std::string, bool> bools;
  // Callbacks: store function names that have callbacks.
  std::unordered_set<std::string> callbacks;  // names of function props
};

// Callback store: jsi::Function refs stored SEPARATELY from PropsSnapshot.
// Only created/accessed/destroyed on JS thread (in setComponentProps).
// Key = "componentId::propName"
static std::unordered_map<std::string, std::shared_ptr<jsi::Function>>& getCallbackStore() {
  static std::unordered_map<std::string, std::shared_ptr<jsi::Function>> store;
  return store;
}

static std::unordered_map<std::string, PropsSnapshot>& getPropsStore() {
  static std::unordered_map<std::string, PropsSnapshot> store;
  return store;
}

extern "C" void ferrum_register_view(const char*, void*) {}
extern "C" void ferrum_unregister_view(const char*) {}

static std::string g_currentRenderingComponent;

extern "C" const char* ferrum_try_render(const char* componentId, void* view, float w, float h) {
  auto &reg = getRenderRegistry();
  auto it = reg.find(std::string(componentId));
  if (it == reg.end()) return nullptr;

  void* runtime_ptr = nullptr;
  void* props_ptr = nullptr;
  auto &store = getPropsStore();
  auto sit = store.find(std::string(componentId));
  if (sit != store.end() && g_runtime) {
    runtime_ptr = reinterpret_cast<void*>(g_runtime);
    props_ptr = reinterpret_cast<void*>(&sit->second);
  }

  g_currentRenderingComponent = std::string(componentId);
  it->second(view, w, h, runtime_ptr, props_ptr);
  g_currentRenderingComponent.clear();
  return "ok";
}

// ─── JSI value access (C wrappers for Rust) ───────────────────────────

extern "C" const char* ferrum_jsi_get_string(void* runtime, void* object, const char* prop_name) {
  if (!runtime || !object) return "";
  auto *snapshot = reinterpret_cast<PropsSnapshot*>(object);
  auto it = snapshot->strings.find(std::string(prop_name));
  if (it != snapshot->strings.end()) {
    static thread_local std::string buf;
    buf = it->second;
    return buf.c_str();
  }
  return "";
}

extern "C" double ferrum_jsi_get_number(void* runtime, void* object, const char* prop_name) {
  if (!runtime || !object) return 0.0;
  auto *snapshot = reinterpret_cast<PropsSnapshot*>(object);
  auto it = snapshot->numbers.find(std::string(prop_name));
  if (it != snapshot->numbers.end()) return it->second;
  return 0.0;
}

extern "C" int ferrum_jsi_get_bool(void* runtime, void* object, const char* prop_name) {
  if (!runtime || !object) return 0;
  auto *snapshot = reinterpret_cast<PropsSnapshot*>(object);
  auto it = snapshot->bools.find(std::string(prop_name));
  if (it != snapshot->bools.end()) return it->second ? 1 : 0;
  return 0;
}

extern "C" int ferrum_jsi_has_prop(void* runtime, void* object, const char* prop_name) {
  if (!runtime || !object) return 0;
  auto *snapshot = reinterpret_cast<PropsSnapshot*>(object);
  std::string name(prop_name);
  return (snapshot->strings.count(name) || snapshot->numbers.count(name) ||
          snapshot->bools.count(name) || snapshot->callbacks.count(name)) ? 1 : 0;
}

extern "C" void ferrum_jsi_call_function(void* runtime, void* object, const char* prop_name) {
  if (!g_runtime || g_currentRenderingComponent.empty()) return;
  auto key = g_currentRenderingComponent + "::" + prop_name;
  auto &cbs = getCallbackStore();
  auto it = cbs.find(key);
  if (it != cbs.end() && it->second) {
    it->second->call(*g_runtime);
  }
}

extern "C" void ferrum_jsi_call_function_with_string(void* runtime, void* object,
                                                      const char* prop_name, const char* arg) {
  if (!g_runtime || g_currentRenderingComponent.empty()) return;
  auto key = g_currentRenderingComponent + "::" + prop_name;
  auto &cbs = getCallbackStore();
  auto it = cbs.find(key);
  if (it != cbs.end() && it->second) {
    it->second->call(*g_runtime, jsi::String::createFromUtf8(*g_runtime, arg));
  }
}

// ─── JSI installation ──────────────────────────────────────────────────

static void installRNARuntime(jsi::Runtime &rt) {
  auto rnaObj = jsi::Object(rt);

  // __rna.callSync(moduleId, fnName, argsJson) → string
  auto callSync = jsi::Function::createFromHostFunction(
      rt,
      jsi::PropNameID::forAscii(rt, "callSync"),
      3,
      [](jsi::Runtime &rt,
         const jsi::Value &,
         const jsi::Value *args,
         size_t count) -> jsi::Value {

        if (count < 3) {
          throw jsi::JSError(rt, "__rna.callSync requires 3 args: moduleId, fnName, argsJson");
        }

        auto moduleId = args[0].asString(rt).utf8(rt);
        auto fnName   = args[1].asString(rt).utf8(rt);
        auto argsJson = args[2].asString(rt).utf8(rt);

        auto key = moduleId + "::" + fnName;
        auto &reg = getRegistry();
        auto it = reg.find(key);
        if (it == reg.end() || !it->second.syncFn) {
          throw jsi::JSError(rt, "Unknown RNA function: " + key);
        }

        const char* result = it->second.syncFn(argsJson.c_str());
        if (!result) return jsi::Value::null();

        return jsi::String::createFromUtf8(rt, result);
      });

  // __rna.callAsync(moduleId, fnName, argsJson) → Promise
  auto callAsync = jsi::Function::createFromHostFunction(
      rt,
      jsi::PropNameID::forAscii(rt, "callAsync"),
      3,
      [](jsi::Runtime &rt,
         const jsi::Value &,
         const jsi::Value *args,
         size_t count) -> jsi::Value {

        if (count < 3) {
          throw jsi::JSError(rt, "__rna.callAsync requires 3 args: moduleId, fnName, argsJson");
        }

        auto moduleId = args[0].asString(rt).utf8(rt);
        auto fnName   = args[1].asString(rt).utf8(rt);
        auto argsJson = args[2].asString(rt).utf8(rt);

        auto key = moduleId + "::" + fnName;
        auto &reg = getRegistry();
        auto it = reg.find(key);
        if (it == reg.end() || !it->second.asyncFn) {
          throw jsi::JSError(rt, "Unknown RNA async function: " + key);
        }

        auto asyncFn = it->second.asyncFn;

        // Create a Promise
        auto Promise = rt.global().getPropertyAsFunction(rt, "Promise");
        auto executor = jsi::Function::createFromHostFunction(
            rt,
            jsi::PropNameID::forAscii(rt, "executor"),
            2,
            [asyncFn, argsJson](jsi::Runtime &rt,
                                const jsi::Value &,
                                const jsi::Value *pargs,
                                size_t) -> jsi::Value {
              // For PoC: call synchronously on the JS thread.
              // Production would dispatch to a background queue.
              auto resolve = std::make_shared<jsi::Function>(pargs[0].asObject(rt).asFunction(rt));
              auto reject  = std::make_shared<jsi::Function>(pargs[1].asObject(rt).asFunction(rt));

              // Raw pointer captures for the C callbacks
              struct Ctx {
                jsi::Runtime *rt;
                std::shared_ptr<jsi::Function> resolve;
                std::shared_ptr<jsi::Function> reject;
              };
              auto ctx = new Ctx{&rt, resolve, reject};

              asyncFn(
                  argsJson.c_str(),
                  [](const char* result) {
                    // Note: PoC simplification — callbacks called on same thread
                  },
                  [](const char* code, const char* msg) {
                  });

              // PoC: just call sync and resolve immediately
              // (proper async dispatch is Phase 2)
              return jsi::Value::undefined();
            });

        return Promise.callAsConstructor(rt, executor);
      });

  // __rna.modules() → list registered module::fn keys (for debugging)
  auto listModules = jsi::Function::createFromHostFunction(
      rt,
      jsi::PropNameID::forAscii(rt, "modules"),
      0,
      [](jsi::Runtime &rt,
         const jsi::Value &,
         const jsi::Value *,
         size_t) -> jsi::Value {
        auto &reg = getRegistry();
        auto arr = jsi::Array(rt, reg.size());
        size_t i = 0;
        for (auto &[key, _] : reg) {
          arr.setValueAtIndex(rt, i++, jsi::String::createFromUtf8(rt, key));
        }
        return arr;
      });

  // In release builds there are no dylibs to load — all native code is statically linked.
#if DEBUG
  auto loadDylib = jsi::Function::createFromHostFunction(
      rt,
      jsi::PropNameID::forAscii(rt, "loadDylib"),
      1,
      [](jsi::Runtime &rt,
         const jsi::Value &,
         const jsi::Value *args,
         size_t count) -> jsi::Value {

        if (count < 1 || !args[0].isString()) {
          throw jsi::JSError(rt, "__rna.loadDylib requires a URL string");
        }

        auto urlStr = args[0].asString(rt).utf8(rt);
        NSURL *url = [NSURL URLWithString:[NSString stringWithUTF8String:urlStr.c_str()]];

        // Synchronous download to app sandbox (PoC — production would be async)
        NSError *err = nil;
        NSLog(@"[FerrumCpp] Downloading dylib from: %@", url);
        // Use NSURLRequest with no-cache policy to bypass NSURLCache
        NSURLRequest *request = [NSURLRequest requestWithURL:url
                                                 cachePolicy:NSURLRequestReloadIgnoringLocalCacheData
                                             timeoutInterval:10.0];
        NSURLResponse *response = nil;
        NSData *data = [NSURLConnection sendSynchronousRequest:request
                                             returningResponse:&response
                                                         error:&err];
        if (!data) {
          auto msg = std::string("Failed to download dylib: ") +
                     (err ? err.localizedDescription.UTF8String : "unknown");
          throw jsi::JSError(rt, msg);
        }

        // Verify we got a Mach-O file (magic: 0xFEEDFACF for 64-bit)
        NSLog(@"[FerrumCpp] Downloaded %lu bytes", (unsigned long)data.length);
        if (data.length >= 4) {
          uint32_t magic = 0;
          [data getBytes:&magic length:4];
          NSLog(@"[FerrumCpp] Magic: 0x%08X (expected 0xFEEDFACF for arm64)", magic);
          if (magic != 0xFEEDFACF && magic != 0xCFFAEDFE) {
            // Not a Mach-O — log first bytes for debugging
            const char *bytes = (const char *)data.bytes;
            NSString *preview = [[NSString alloc] initWithBytes:bytes
                                                         length:MIN(100, data.length)
                                                       encoding:NSUTF8StringEncoding];
            NSLog(@"[FerrumCpp] Not Mach-O! First bytes: %@", preview ?: @"(binary)");
            throw jsi::JSError(rt, "Downloaded data is not a valid Mach-O dylib");
          }
        }

        // Write to sandbox with unique name (timestamp-based)
        NSString *docsDir = NSSearchPathForDirectoriesInDomains(
            NSDocumentDirectory, NSUserDomainMask, YES).firstObject;
        NSString *dylibDir = [docsDir stringByAppendingPathComponent:@"ferrum_dylibs"];
        [[NSFileManager defaultManager] createDirectoryAtPath:dylibDir
                                  withIntermediateDirectories:YES
                                                  attributes:nil
                                                       error:nil];

        // Use a unique filename so dlopen sees it as a new library
        NSString *filename = [NSString stringWithFormat:@"rna_%llu.dylib",
                              (unsigned long long)[[NSDate date] timeIntervalSince1970] * 1000];
        NSString *localPath = [dylibDir stringByAppendingPathComponent:filename];
        [data writeToFile:localPath atomically:YES];

        // dlopen with RTLD_GLOBAL so symbols from shared dylibs (native.dylib)
        // are available to subsequently loaded component dylibs.
        void *handle = dlopen(localPath.UTF8String, RTLD_NOW | RTLD_GLOBAL);
        if (!handle) {
          auto msg = std::string("dlopen failed: ") + (dlerror() ?: "unknown");
          NSLog(@"[FerrumCpp] %s", msg.c_str());
          throw jsi::JSError(rt, msg);
        }

        NSLog(@"[FerrumCpp] Hot-reloaded dylib: %@", localPath);
        return jsi::Value(true);
      });
#endif

  // __rna.setComponentProps(componentId, propsObject)
  // Just stores the JSI props. Fabric's updateProps (triggered by propsJson change)
  // handles the re-render via ferrum_try_render.
  auto setComponentProps = jsi::Function::createFromHostFunction(
      rt,
      jsi::PropNameID::forAscii(rt, "setComponentProps"),
      2,
      [](jsi::Runtime &rt,
         const jsi::Value &,
         const jsi::Value *args,
         size_t count) -> jsi::Value {
        if (count < 2 || !args[0].isString()) return jsi::Value::undefined();

        auto componentId = args[0].asString(rt).utf8(rt);
        auto &store = getPropsStore();

        if (args[1].isObject()) {
          auto obj = args[1].asObject(rt);
          PropsSnapshot snap;

          // Snapshot all properties into plain C++ maps — no JSI references stored
          auto names = obj.getPropertyNames(rt);
          for (size_t i = 0; i < names.size(rt); i++) {
            auto name = names.getValueAtIndex(rt, i).getString(rt).utf8(rt);
            auto val = obj.getProperty(rt, jsi::PropNameID::forUtf8(rt, name));
            if (val.isString()) {
              snap.strings[name] = val.asString(rt).utf8(rt);
            } else if (val.isNumber()) {
              snap.numbers[name] = val.asNumber();
            } else if (val.isBool()) {
              snap.bools[name] = val.getBool();
            } else if (val.isObject() && val.asObject(rt).isFunction(rt)) {
              snap.callbacks.insert(name);
              // Store the actual jsi::Function in a separate map (JS thread only)
              auto key = componentId + "::" + name;
              getCallbackStore()[key] = std::make_shared<jsi::Function>(
                val.asObject(rt).asFunction(rt));
            }
          }
          // obj goes out of scope here — jsi::Object destroyed on JS thread (safe)

          store[componentId] = std::move(snap);
        } else {
          store.erase(componentId);
        }

        return jsi::Value::undefined();
      });

  rnaObj.setProperty(rt, "callSync", std::move(callSync));
  rnaObj.setProperty(rt, "callAsync", std::move(callAsync));
  rnaObj.setProperty(rt, "modules", std::move(listModules));
#if DEBUG
  rnaObj.setProperty(rt, "loadDylib", std::move(loadDylib));
#endif
  rnaObj.setProperty(rt, "setComponentProps", std::move(setComponentProps));

  rt.global().setProperty(rt, "__rna", std::move(rnaObj));
  g_runtime = &rt;  // Store for render function prop access
  NSLog(@"[FerrumCpp] __rna installed with %lu registered functions", (unsigned long)getRegistry().size());
}

// ─── TurboModule with JSI bindings ─────────────────────────────────────
// Codegen-backed TurboModule. RN calls installJSIBindingsWithRuntime:
// when the module is first accessed → installs global.__rna.
// No dependency on expo-ferrum/react-native-ferrum.

#import <React/RCTBridgeModule.h>
#import <ReactCommon/RCTTurboModule.h>
#import <ReactCommon/RCTTurboModuleWithJSIBindings.h>
#import <ReactCommon/CallInvoker.h>

#if __has_include(<NativFabricSpec/NativFabricSpec.h>)
#import <NativFabricSpec/NativFabricSpec.h>
#elif __has_include(<ReactCodegen/NativFabricSpec.h>)
#import <ReactCodegen/NativFabricSpec.h>
#elif __has_include("NativFabricSpec.h")
#import "NativFabricSpec.h"
#endif

@interface RNARuntimeModule : NSObject <NativeRNARuntimeSpec, RCTTurboModuleWithJSIBindings>
@end

@implementation RNARuntimeModule

RCT_EXPORT_MODULE(RNARuntime)

- (NSDictionary *)getConstants {
  return @{};
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params {
  return std::make_shared<facebook::react::NativeRNARuntimeSpecJSI>(params);
}

- (void)installJSIBindingsWithRuntime:(facebook::jsi::Runtime &)runtime
                          callInvoker:(const std::shared_ptr<facebook::react::CallInvoker> &)callinvoker
{
  installRNARuntime(runtime);
}

+ (BOOL)requiresMainQueueSetup {
  return NO;
}

+ (NSString *)moduleName {
  return @"RNARuntime";
}

@end

// Keep ferrum_cpp_install for backward compatibility with expo-ferrum (if installed)
extern "C" void ferrum_cpp_install(void *runtimePtr) {
  if (!runtimePtr) return;
  auto &rt = *reinterpret_cast<jsi::Runtime *>(runtimePtr);
  installRNARuntime(rt);
}

